name: deploy

on:
  push:
    branches:
      - deploy
env:
  GOOSE_REDIS_HOST: redis
  GOOSE_REDIS_PORT: 6379
  GOOSE_RABBITMQ_HOST: rabbitmq
  GOOSE_RABBITMQ_PORT: 5672
  GOOSE_RABBITMQ_USERNAME: guest
  GOOSE_RABBITMQ_PASSWORD: guest
jobs:

  build:
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis:7.0
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: heidiks/rabbitmq-delayed-message-exchange:3.9.13-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup up java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1409

      - name: Env
        run: env

      - name: Execute clojure code
        run: |
          clojure -X:console
